#pragma config(Sensor, S1,     leftBumper,     sensorTouch)
#pragma config(Sensor, S2,     rightBumper,    sensorTouch)
#pragma config(Sensor, S3,     fearLight,      sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
* THIS ROBOT CONTROLS THE TOP LIGHT SENSOR, AND THE TWO BUMPERS
*/

ubyte data[] = {'n', 'n', 'n'};

task main()
{
	nxtEnableHSPort();
	nxtSetHSBaudRate(9600);  // can go as high as 921600 BAUD
	nxtHS_Mode = hsRawMode;
	wait1Msec(2000);
}

void transmitData()
{
	nxtWriteRawHS(&data[0], 3);
}
